version: '3.3'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: delikatesla/api_yamdb:v1.0
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./static_volume:/code/static/
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.10
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static_volume:/code/static/
    depends_on:
      - web
    ports:
      - "80:80"

